version 3.8
services
  gameapptestauso123
    image amalan06gameappnewimagelatest
    build .
    container_name gameappautotest123
    ports
      - 803000
    environment
       - PORT=3000
    volumes
      - .app
    command [node, app.js]
 